### ISSUE TITLE
`gdal-static` CI is failing

### ISSUE THREAD

**Issue by lnicola** [georust/gdal#571]
>     Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)

Maybe we need to install `libsqlite3-dev`?

CC @weiznich

**Comment by weiznich** [comment]
Installing libsqlite shouldn't be required there as we explicitly enable the bundled feature for the static gdal builds. Do you have a link to a failed run? Maybe I find some time to look into this in the next days.

**Comment by lnicola** [comment]
You're right, of course. It's actually the proj build script. The CI workflow actually installs SQLite on Windows for it.

https://github.com/georust/gdal/actions/runs/11351540834/job/31572334212

**Comment by weiznich** [comment]
Proj needs the sqlite3 binary (not library) as it builds the proj.db at build time. It's strange that the error message above talks about the library and includes. That should (and must) use the same static version as gdal as we otherwise get duplicated symbols. Was there a proj-rs release in the last few days?

**Comment by lnicola** [comment]
I think GitHub switched ubuntu-latest to 24.04.
